export const ADD_LOST_RECORD = "ADD_LOST_RECORD";
export const FETCH_LOST_RECORDS = "FETCH_LOST_RECORDS";

export const ADD_FOUND_RECORD = "ADD_FOUND_RECORD";
export const FETCH_FOUND_RECORDS = "FETCH_FOUND_RECORDS";

export const ADD_NEW_USER = "ADD_NEW_USER";
export const CHANGE_AUTH = "CHANGE_AUTH";
export const GET_USER_BY_ID = "GET_USER_BY_ID"
export const EDIT_USER = "EDIT_USER"

export const FETCH_POSTS = "FETCH_POSTS"
export const ADD_POST = "ADD_POST"
export const CHANGE_ADD_POST = "CHANGE_ADD_POST"
export const FETCH_POST_BY_ID = "FETCH_POST_BY_ID"

export const ADD_COMMENT = "ADD_COMMENT"
