export const ADD_LOST_RECORD = "ADD_LOST_RECORD";
export const FETCH_LOST_RECORDS = "FETCH_LOST_RECORDS";

export const ADD_FOUND_RECORD = "ADD_FOUND_RECORD";
export const FETCH_FOUND_RECORDS = "FETCH_FOUND_RECORDS";

export const ADD_NEW_USER = "ADD_NEW_USER";
export const CHANGE_AUTH = "CHANGE_AUTH";
